/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsNewRouteImport } from './routes/leads.new'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as BikesNewRouteImport } from './routes/bikes.new'
import { Route as BikesBikeIdEditRouteImport } from './routes/bikes.$bikeId.edit'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesNewRoute = BikesNewRouteImport.update({
  id: '/bikes/new',
  path: '/bikes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesBikeIdEditRoute = BikesBikeIdEditRouteImport.update({
  id: '/bikes/$bikeId/edit',
  path: '/bikes/$bikeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bikes/new': typeof BikesNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/leads/': typeof LeadsIndexRoute
  '/bikes/$bikeId/edit': typeof BikesBikeIdEditRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bikes/new': typeof BikesNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/leads': typeof LeadsIndexRoute
  '/bikes/$bikeId/edit': typeof BikesBikeIdEditRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bikes/new': typeof BikesNewRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/leads/new': typeof LeadsNewRoute
  '/leads/': typeof LeadsIndexRoute
  '/bikes/$bikeId/edit': typeof BikesBikeIdEditRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bikes/new'
    | '/leads/$leadId'
    | '/leads/new'
    | '/leads/'
    | '/bikes/$bikeId/edit'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bikes/new'
    | '/leads/$leadId'
    | '/leads/new'
    | '/leads'
    | '/bikes/$bikeId/edit'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/bikes/new'
    | '/leads/$leadId'
    | '/leads/new'
    | '/leads/'
    | '/bikes/$bikeId/edit'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BikesNewRoute: typeof BikesNewRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsNewRoute: typeof LeadsNewRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  BikesBikeIdEditRoute: typeof BikesBikeIdEditRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/new': {
      id: '/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/new': {
      id: '/bikes/new'
      path: '/bikes/new'
      fullPath: '/bikes/new'
      preLoaderRoute: typeof BikesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/$bikeId/edit': {
      id: '/bikes/$bikeId/edit'
      path: '/bikes/$bikeId/edit'
      fullPath: '/bikes/$bikeId/edit'
      preLoaderRoute: typeof BikesBikeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BikesNewRoute: BikesNewRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsNewRoute: LeadsNewRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  BikesBikeIdEditRoute: BikesBikeIdEditRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
